export const CURRENT_POKEMON_SET = "CURRENT_POKEMON_SET";
export const CURRENT_PAGINATION_OFFSET_SET = "CURRENT_PAGINATION_OFFSET_SET";
export const POKEMON_TOTAL_COUNT_SET = "POKEMON_TOTAL_COUNT_SET";
export const POKEMON_LIST_SET = "POKEMON_LIST_SET";
export const POKEMON_LIST_ADD = "POKEMON_LIST_ADD";
